# Generated by Django 4.0.3 on 2022-11-07 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regnumber', models.CharField(max_length=16, null=True)),
                ('Firstname', models.CharField(max_length=24, null=True)),
                ('Middlename', models.CharField(max_length=26, null=True)),
                ('Lastname', models.CharField(max_length=26)),
                ('StudentEmail', models.EmailField(max_length=42, unique=True)),
                ('IDnumber', models.CharField(max_length=9)),
                ('ResultsSlip', models.ImageField(null=True, upload_to='image/')),
                ('frontID', models.ImageField(null=True, upload_to='image/')),
                ('coursename', models.CharField(max_length=23, null=True)),
                ('status', models.CharField(default='UNAPPROVED', max_length=16)),
                ('Telephonenumber', models.CharField(max_length=16, null=True)),
                ('Address', models.CharField(max_length=36, null=True)),
                ('Gender', models.CharField(max_length=12, null=True)),
                ('DOB', models.DateTimeField(null=True)),
                ('photo', models.ImageField(default=False, upload_to='image/')),
                ('Parent_name', models.CharField(max_length=22)),
                ('parent_email', models.EmailField(max_length=36)),
                ('ParentTelephonenumber', models.CharField(max_length=14)),
                ('Timeregistered', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
