# Generated by Django 4.0.3 on 2022-11-12 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms', '0001_initial'),
        ('payment', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_code', models.CharField(max_length=19, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('school_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subjectcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('dept_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.department')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectRegistration',
            fields=[
                ('registration_id', models.AutoField(max_length=14, primary_key=True, serialize=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.studentreg')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.subjects')),
                ('term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.semesterfees')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('present', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.subjectregistration')),
            ],
        ),
    ]
