# Generated by Django 4.0.3 on 2022-11-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectregistration',
            name='registration_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
