# Generated by Django 4.0.3 on 2022-11-15 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
        ('payment', '0002_alter_payment_telephone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='telephone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semesterfees',
            name='year',
            field=models.CharField(max_length=7),
        ),
        migrations.CreateModel(
            name='Feesdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='INCOMPLETE', max_length=12)),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.semesterfees')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.studentreg')),
            ],
        ),
    ]
