# Generated by Django 4.0.3 on 2022-11-12 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturers',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Lecturernumber', models.CharField(max_length=20, unique=True)),
                ('Title', models.CharField(max_length=16)),
                ('Firstname', models.CharField(max_length=34)),
                ('Middlename', models.CharField(blank=True, max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telephonenumber', models.CharField(max_length=22)),
                ('address', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=15)),
                ('IDnumber', models.CharField(max_length=15)),
                ('is_staff', models.BooleanField(default=True)),
                ('status', models.CharField(default='Inactive', max_length=16)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('Timeregistered', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.department')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_number', models.CharField(max_length=20, unique=True)),
                ('Title', models.CharField(max_length=16)),
                ('Firstname', models.CharField(max_length=34)),
                ('Middlename', models.CharField(max_length=30, null=True)),
                ('Lastname', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Telephonenumber', models.CharField(max_length=22, unique=True)),
                ('Address', models.CharField(max_length=40)),
                ('Gender', models.CharField(max_length=15)),
                ('IDnumber', models.CharField(max_length=15, unique=True)),
                ('status', models.CharField(default='Inactive', max_length=16)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('Timeregistered', models.DateTimeField(verbose_name='auto_now_add:True')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
