# Generated by Django 4.0.3 on 2022-11-16 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0004_alter_admins_timeregistered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='id',
        ),
        migrations.AlterField(
            model_name='admins',
            name='Admin_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='admins',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
